env:
    - DEFINITION=5.3.27
    - DEFINITION=5.4.20
    - DEFINITION=5.5.4

script: ./run-tests.sh $DEFINITION

before_install:
    - sudo apt-get update -qq
    - sudo apt-get build-dep php5-cli
    - sudo apt-get install -qq git-core libmcrypt-dev

before_script:
    - git clone http://github.com/sstephenson/bats
    - bats/install.sh $HOME
    - export PATH=$HOME/bin:$HOME/libexec:$PATH
    - bats --version
