os:
  - linux
  - osx

env:
    - DEFINITION=5.2.17 PHP_BUILD_CONFIGURE_OPTS="--with-libdir=lib/x86_64-linux-gnu"
    - DEFINITION=5.3.3 PHP_BUILD_CONFIGURE_OPTS="--with-libdir=lib/x86_64-linux-gnu"
    - DEFINITION=5.3.29
    - DEFINITION=5.4.45
    - DEFINITION=5.5.30
    - DEFINITION=5.6.15
    - DEFINITION=7.0.0RC6

script: ./run-tests.sh $DEFINITION

before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get build-dep php5-cli; fi
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install -qq git-core libmcrypt-dev libjpeg-dev libreadline-dev; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew tap homebrew/versions; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install re2c; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install libjpeg; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install libmcrypt; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install autoconf; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew install bison27; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew link bison27 --force; fi


before_script:
    - git clone https://github.com/sstephenson/bats
    - bats/install.sh $HOME
    - export PATH=$HOME/bin:$HOME/libexec:$PATH
    - bats --version

after_failure:
    - sudo cat $(ls -r /tmp/php-build*.log | head -n 1)

matrix:
  allow_failures:
    - os: osx