sudo: false
language: c

cache:
  apt: true
  directories:
    - $HOME/Library/Caches/Homebrew

addons:
  apt:
    sources:
      - sourceline: 'ppa:ondrej/php'
    packages:
      - libmcrypt-dev
      - libtidy-dev
      - libicu-dev
      - libzip-dev
      - php5-cli
      - re2c
    update: true
  homebrew:
    packages:
      - re2c
      - libmcrypt
      - openssl
      - libxml2
      - icu4c
      - libzip
    update: true

env:
  global:
    - PHP_BUILD_EXTRA_MAKE_ARGUMENTS="-j2"

matrix:
  include:
  - os: linux
    env:
    - DEFINITION=5.2.17
  - os: linux
    env:
    - DEFINITION=5.3.29
  - os: linux
    env:
    - DEFINITION=5.4.45
  - os: linux
    env:
    - DEFINITION=5.5.38
  - os: linux
    env:
    - DEFINITION=5.6.38
  - os: linux
    env:
    - DEFINITION=7.0.32
  - os: linux
    env:
    - DEFINITION=7.1.24
  - os: linux
    env:
    - DEFINITION=7.2.12
  - os: linux
    env:
    - DEFINITION=7.3.0RC5
  - os: osx
    osx_image: xcode8
    env:
    - DEFINITION=5.2.17
  - os: osx
    osx_image: xcode8.3
    env:
    - DEFINITION=5.3.29
  - os: osx
    osx_image: xcode8.3
    env:
    - DEFINITION=5.4.45
  - os: osx
    osx_image: xcode8.3
    env:
    - DEFINITION=5.5.38
  - os: osx
    osx_image: xcode9.4
    env:
    - DEFINITION=5.6.38
  - os: osx
    osx_image: xcode9.4
    env:
    - DEFINITION=7.0.32
  - os: osx
    osx_image: xcode10
    env:
    - DEFINITION=7.1.24
  - os: osx
    osx_image: xcode10
    env:
    - DEFINITION=7.2.12
  - os: osx
    osx_image: xcode10
    env:
    - DEFINITION=7.3.0RC5
  - os: osx
    osx_image: xcode10
    env:
    - DEFINITION=7.2.12
    - USE_HOMEBREW_OPENSSL=no
  - os: osx
    osx_image: xcode10
    env:
    - DEFINITION=7.3.0RC5
    - USE_HOMEBREW_OPENSSL=no

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        if [[ "$DEFINITION" =~ ^("5.2.".*|"5.3."[0-6])$ ]]; then
            export PHP_BUILD_CONFIGURE_OPTS="--with-libdir=lib/x86_64-linux-gnu"
        fi
        if [[ "$DEFINITION" =~ ^("5.2.".*|"5.3.".*)$ ]]; then
            sudo apt-get install -y autoconf2.13
            export PHP_AUTOCONF=/usr/bin/autoconf2.13
        fi
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        if [[ "$DEFINITION" =~ ^("5."[23]|"5.4."([0-9]|1[0-4])$) ]]; then
            export LIBS="-lssl -lcrypto"
        fi
        if [[ "$DEFINITION" == "5.2.17" ]]; then
            brew install --verbose mysql@5.7 | awk '/^==>/ { print $0 } NR % 100 == 0 { printf "." ; fflush() }'
            export PHP_BUILD_CONFIGURE_OPTS="$PHP_BUILD_CONFIGURE_OPTS --with-mysql=$(brew --prefix mysql@5.7) --with-mysqli=$(brew --prefix mysql@5.7)/bin/mysql_config --with-pdo-mysql=$(brew --prefix mysql@5.7)"
        fi
        if [[ "$DEFINITION" =~ ^("5.2.".*|"5.3.".*)$ ]]; then
            brew install autoconf@2.13
            export PHP_AUTOCONF=$(brew --prefix autoconf@2.13)/bin/autoconf213
        fi
        if [[ "$TRAVIS_OSX_IMAGE" =~ "xcode"("7"|"8")("."|$) ]] || [[ "$TRAVIS_OSX_IMAGE" =~ "xcode9"$ ]]; then
            brew link --force libxml2
        fi
        if [[ "$USE_HOMEBREW_OPENSSL" = "no" ]]; then
            brew uninstall --ignore-dependencies openssl
        fi
    fi

install:
  - git clone https://github.com/sstephenson/bats
  - bats/install.sh $HOME
  - export PATH=$HOME/bin:$HOME/libexec:$PATH
  - bats --version

script:
  - ./run-tests.sh $DEFINITION

after_failure:
  - |
    export PHP_CONFIG_LOG_PATH="$(ls -r /var/tmp/php-build/source/*/config.log | head -n 1)"
    if [[ -n "$PHP_CONFIG_LOG_PATH" ]]; then
      tail -1000 $PHP_CONFIG_LOG_PATH
    fi
  - |
    export PHP_BUILD_LOG_PATH="$(ls -r /tmp/php-build*.log | head -n 1)"
    if [[ -n "$PHP_BUILD_LOG_PATH" ]]; then
      tail -1000 $PHP_BUILD_LOG_PATH
    fi
